### ISSUE TITLE
Format de donnée de sortie

### ISSUE THREAD

**Issue by FauconFan** [IP7/concours_runner#2]
Pour l'instant, le format respecte cette classe.

```
class ResTest(object):
	def __init__(self, test_id):
		self.test_id = test_id
		self.res_contents = {}
		self.compile_success = True
```

res_contents ait un dict qui a pour clé l'entrée et en valeur un tuple de 3 membres, le premier est le code de sortie, le deuxième est la sortie écrite par le programme et le denier est un booléen qui donne si le test est passé ou non.

**Comment by FauconFan** [comment]
Est-ce que lors de la compilation on donne le message d'erreur, auquel cas il faut le mettre dans ResTest

**Comment by Peaupote** [comment]
Ca me semble bien.

Dans ma base de données j'ai un booléen qui me dit si le test est passé et un `text` qui contient les logs du compilateur donc c'est à peu près ça. Je me charge d'écrire dedans.

Tu ne dois pas compiler pour chaque test, si ? On peut vouloir changer la structure utilisée en fonction de la manière dont on fait communiquer les programmes. Par exemple, si on fait des sockets, ça pourrait être sympa d'avoir l'affichage en direct dans le navigateur des logs du compilateur. Dans ce cas, pas besoin de les retourner à la fin, il suffit des les écrire directement dans le flux du socket. 

La seule chose dont j'ai absolument besoin c'est de savoir si un test est passé ou non. Si on utilise des sockets, ce que tu as fait me semble bien.

**Comment by FauconFan** [comment]
Alors là se pose une autre question, d'abord faut établir un protocole de communication, ensuite est-ce qu'on passe par une socket ? J'ai jamais manipulé ce genre de trucs.

Je recompile pas à chaque test. Les tests se font en 2 temps : la compilation puis l'éxécution de tous les tests.

Ensuite est-ce qu'il faut que le programme soit toujours accessible. "Qu'il tourne en fond". Donc doit fork pour continuer à écouter sur le flux principal si il y a un nouveau test à faire, pendant que le fils éxécute les tests.

Dans cette même mécanique, est-ce qu'il faut avoir un conteneur différent pour chaque test ?

Pour l'instant, le programme commence, fait les tests de manière pûrement linéaire, affiche le résultat et se termine.

De quelle manière le programme devrait se comporter ?

**Comment by Peaupote** [comment]
Le comportement que tu décris ressemble beaucoup à ce que j'avais imaginé que tu ferais, donc on n'a probablement rien à changer là dessus.

Si on fait des sockets, il faudrait juste que tu écrives la sortie des tests dans un flux que je reçoive et que je puisse parser; en JSON par exemple. Si on fait simplement des requêtes POST, c'est pareil mais t’envoies tout d'un coup. 

Dans tous les cas, je ne pense pas que ça représente beaucoup de changements de ton côté. Une fois qu'on aura établit le contact, il n'y aura plus qu'à modifier l'interface utilisateur en js.

**Comment by FauconFan** [comment]
J'ai automatisé la notion de tâche, et il fait maintenant le pull et l'éxécution de tous les tests en parallèle.
Ca à l'air bien. La prochaine étape, serait, de se mettre d'accord sur ce format de donnée, ça me va très bien le json. Je compte pas le faire tout de suite, alors faudra voir le jour où on va tout connecter

**Comment by Peaupote** [comment]
Eh bien pour le format de donné j'imagine un truc assez simple.
Pour la compilation, simplement le texte générée sr la sortie standard.
Pour chaque test, on peut se limiter à un entier je pense.

0. erreur d’exécution
1. temps d’exécution trop long (boucle infinie)
2. plus de mémoire
3. mauvaise sortie
4. OK

**Comment by FauconFan** [comment]
J'établirai un code de retour claire, je suis pas sur que le plus de mémoire est faisable facilement par exemple...

**Comment by FauconFan** [comment]
Ensuite, suite à la parallélisme des tâches, on recompile le code à chaque test. Est-ce que ça change quelque chose, de ton côté ?

**Comment by FauconFan** [comment]
Suite de la discussion ici https://github.com/orgs/IP7/teams/dev_concours/discussions/1
