### ISSUE TITLE
Communication UI / runner

### ISSUE THREAD

**Issue by FauconFan** [IP7/concours_runner#3]
Comment on communique entre le runner et le site web ? Une bdd, un socket, un fichier ?

**Comment by Peaupote** [comment]
* On ne va clairement pas faire une base de données, c'est pas fait pour ça.
* Le socket est la solution la plus intéressante à programmer (me concernant en tout cas, parce que je n'en ai jamais fait et que le rendu est plutôt cool) mais avant de se lancer je préfère me documenter un peu.
* Le fichier... C'est un peu le socket du pauvre non ? on peut se le permettre parce qu'on est sur la même machine mais c'est pas une bonne solution je trouve.
* Sinon, j'avais pensé à juste faire une requête en POST que tu recevrais, parce que c'est facile à faire et qu'on peut envoyer des fichiers. Cela dit c'est vraiment pas top je trouve, parce que tu devrais insérer dans la base de donnée et que l'utilisateur serait obligé d'actualiser en permanence pour avoir les résultats.

**Comment by FauconFan** [comment]
On est vraiment sur la même machine ? On en sait rien, nan ? A priori, l'UI serait quelque part, et le runner sur un serveur puissant... Est-ce que les sockets fonctionnent sur différentes machines ? Et la sécurité là dedans on en fait quoi ? Vu qu'on compte utiliser le code un jour et qu'il est open source, on peut pas se permettre d'avoir une clé privée quelque part....

**Comment by FauconFan** [comment]
J'ai adapté le code pour avoir un flux continu. Donc recevoir une entrée depuis un flux et la renvoyer.

Est-ce qu'un flux est ouvert à chaque tâche ?
Est-ce qu'il faut gérer les collisions ? (2 tâches envoyés, avant que la première n'est pas fini)

**Comment by Peaupote** [comment]
Je pense que ta question est causée par une petite incompréhension entre nous. Pour chaque équipe qui envoi un test, on créer un flux. J'écris sur le flux le fichier à compiler. Tu lis le fichier et tu écris sur le flux un la sortie de la compilation puis des tests successifs. Donc on ne peux pas avoir de collisions

**Comment by FauconFan** [comment]
C'est justement pour ça que je pose la question, comme ça c'est bien clair ^^.

Du coup, nouvelle question : comment fait mon programme pour savoir sur quel socket écouté. Est-ce qu'on a une socket constante qui se contente juste d'envoyer la nouvelle socket pour chaque requête.

**Comment by FauconFan** [comment]
Suite de la discussion ici https://github.com/orgs/IP7/teams/dev_concours/discussions/2
